ministryofjustice/money-to-prisoners-cashbook

bower.json
mtp_cashbook/assets-src/stylesheets/_colours.scss
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/components/_subheader.scss
mtp_cashbook/assets-src/stylesheets/components/_summary_boxes.scss
mtp_cashbook/settings/base.py
mtp_cashbook/templates/base.html
mtp_cashbook/templates/core/index.html
package.json
tasks/sass.js
tasks/scripts.js

This is pretty much "[Style home page summary boxes](https://github.com/ministryofjustice/money-to-prisoners/pull/9)" and "[HTML template and internal styling](https://github.com/ministryofjustice/money-to-prisoners/pull/7)" for Django.

Apply GOV.UK styling using Mojular framework

---

mtp_cashbook/apps/mtp_auth/__init__.py
mtp_cashbook/apps/mtp_auth/api_client.py
mtp_cashbook/apps/mtp_auth/backends.py
mtp_cashbook/apps/mtp_auth/models.py
mtp_cashbook/apps/mtp_auth/tests/test_api_client.py
mtp_cashbook/apps/mtp_auth/tests/test_views.py
mtp_cashbook/templates/base.html

This makes an extra query to `/users/<username>/` during the authentication process so that request.user and its user data can be cached and accessed by views/templates.

Add user data to User Model

---

bower.json
mtp_cashbook/assets-src/stylesheets/elements/_subheader.scss
mtp_cashbook/assets-src/stylesheets/elements/_user-details.scss
mtp_cashbook/settings/base.py
mtp_cashbook/templates/base.html

As PM I'd like alpha branding on the site and tools so staff and citizens do not think it is a finished product ([#95958206](https://www.pivotaltracker.com/story/show/95958206))
**Note:** this merges into internal-template (#33).

Alpha branding

---

mtp_cashbook/assets-src/javascripts/modules/moj.messages.js
mtp_cashbook/assets-src/stylesheets/_colours.scss
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/elements/_messages.scss
mtp_cashbook/templates/base.html

As a monies clerk I'd like errors & flash messages to be clearly defined so I fix them appropriately - ([#93457302](https://www.pivotaltracker.com/story/show/93457302))
**Note:** this merges into alpha-branding branch (#34).

Notification style

---

mtp_cashbook/assets-src/javascripts/modules/moj.messages.js
mtp_cashbook/assets-src/javascripts/modules/moj.running-total.js
mtp_cashbook/assets-src/stylesheets/_$breakpoints.scss
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/transaction_batch_list.html

As a monies clerk I'd like a running total of payments I've credited so I don't have to calculate it myself - ([98802420](https://www.pivotaltracker.com/story/show/98802420))

Add running total to batch process view

---

mtp_cashbook/assets-src/javascripts/modules/moj.dialog.js
mtp_cashbook/assets-src/javascripts/modules/moj.print.js
mtp_cashbook/assets-src/stylesheets/_@print.scss
mtp_cashbook/assets-src/stylesheets/_utilities.scss
mtp_cashbook/assets-src/stylesheets/app-print.scss
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/elements/_checkbox.scss
mtp_cashbook/assets-src/stylesheets/elements/_dialog.scss
mtp_cashbook/assets-src/stylesheets/elements/_table.scss
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html

As a monies clerk I'd like the batch view to be printable, because I have to print - ([#99023134](https://www.pivotaltracker.com/story/show/99023134))

Batch print layout

---

bower.json
mtp_cashbook/assets-src/javascripts/modules/moj.dialog.js
mtp_cashbook/assets-src/stylesheets/_base.scss
mtp_cashbook/assets-src/stylesheets/elements/_subheader.scss
mtp_cashbook/templates/cashbook/transaction_batch_list.html

- Update mojular to include HTML5 shiv
- Fix some spacing issues

IE improvements

---

bower.json
mtp_cashbook/assets-src/javascripts/modules/moj.running-total.js
mtp_cashbook/assets-src/javascripts/modules/moj.sticky-header.js
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/transaction_batch_list.html

As a monies clerk I'd like the control total to remain visible at all times so it can be monitored

Sticky totals

---

bower.json

- Fixes main content skiplink not working
**Fixes:** Ticket [#101755640](https://www.pivotaltracker.com/story/show/101755640) in Pivotal

Bump Mojular dep to 0.5.2

---

mtp_cashbook/apps/core/templatetags/core.py
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/elements/_form-validation.scss
mtp_cashbook/assets-src/stylesheets/elements/_forms.scss
mtp_cashbook/settings/base.py
mtp_cashbook/templates/base.html
mtp_cashbook/templates/mtp_auth/login.html
requirements/base.txt

As a user, I want the login screen to be branded the same as the website, so that it feels like a single experience
- Add basic validation pattern
- Restructure markup for error handling

Make sign in view inline with rest of UI

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_forms.py
mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/apps/cashbook/urls.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/elements/_content-header.scss
mtp_cashbook/assets-src/stylesheets/elements/_summary-boxes.scss
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/includes/locked_buttons.html
mtp_cashbook/templates/cashbook/includes/table_actions.html
mtp_cashbook/templates/cashbook/transactions_locked.html

As a monies clerk, I want to unlock transactions locked to another member of my team so that I can work on them.

Discard locked transactions

---

Dockerfile
README.md
bower.json
gulpfile.js
package.json
tasks/_paths.js
tasks/clean-css.js
tasks/clean-images.js
tasks/clean-js.js
tasks/clean.js
tasks/images.js
tasks/lint.js
tasks/minify-css.js
tasks/minify-scripts.js
tasks/sass.js
tasks/scripts.js
tasks/serve.js
tasks/vendor-css.js

Improve the state of the gulp tasks, including:
- Removing unused packages/tasks
- Swapping [ruby sass](https://github.com/sindresorhus/gulp-ruby-sass) for [libsass](https://github.com/dlmanning/gulp-sass)
- Add gulp JS to linting and fix current warnings

Gulp improvements

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/includes/batch_buttons.html
mtp_cashbook/templates/cashbook/includes/table_actions.html

As a monies clerk
I want to be able to release a batch without processing it 
So that others can process it

Update language for transactions 'cancel' button

---

mtp_cashbook/templates/cashbook/transaction_batch_list.html

As a monies clerk
I want to be warned if I leave the batch screen and I have ticked some transactions 
So that I submit my credited transactions

Update copy on unload prompt

---

mtp_cashbook/templates/cashbook/transaction_batch_list.html

As described at https://www.pivotaltracker.com/story/show/103513830

display the prisoner's name in the transaction table

---

mtp_cashbook/settings/jenkins.py
requirements/jenkins.txt

This configures django-jenkins so that jenkins can run unit tests and generate reports.

Add jenkins config files for running tests

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/assets-src/javascripts/modules/moj.batch-validation.js
mtp_cashbook/templates/cashbook/transaction_batch_list.html

As a monies clark,
I want to be given an error when I submit a batch without ticking any payment,
So that I know I have made an error
[Finishes #104079856]

Change empty batch submission validation to server side

---

bower.json
mtp_cashbook/settings/base.py

Part of multiple PRs to add GA across all MTP apps

read env variable to set GA tracking ID [updates #103597472]

---

mtp_cashbook/templates/mtp_auth/login.html

as specified on https://docs.google.com/document/d/1uAj9CbCS3MMUSVLaMLtqT4qrnYtjZa0wb_nGLxaB3cI/edit

update copy for title [updates #106947332]

---

bower.json

in order to get the new feedback link copy
https://www.pivotaltracker.com/n/projects/1214032/stories/106947332

use latest version of common assets

---

mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/dashboard.html
test/features/user_signout.feature

From changes on https://docs.google.com/document/d/1uAj9CbCS3MMUSVLaMLtqT4qrnYtjZa0wb_nGLxaB3cI/edit

update home page copy [closes #106947908]

---

bower.json
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/dashboard.html

Update the proposition and remove the home page title

---

mtp_cashbook/templates/cashbook/dashboard.html

Keep the page title, but small

---

mtp_cashbook/settings/base.py
mtp_cashbook/settings/prod.py

tightens security for cookies and provides another layer to enforce SSL

---

mtp_cashbook/apps/cashbook/urls.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/javascripts/modules/moj.running-total.js
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/includes/batch_buttons.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
test/features/user_signout.feature

Implement the new credit page designs

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/includes/batch_buttons.html
mtp_cashbook/templates/cashbook/includes/print_dialog.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
test/features/new_credits.feature
test/features/pages/new_credits.js
test/features/steps/cashbook.js
test/features/steps/shared.js

Additionally, removes unused markup on history page
[Updates #106947502]

Adds more copy changes

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/includes/locked_buttons.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html

- removed 'locked' terminology
- change submit button to Done, like credits page
- new label next to Done button
- Home link,, like credits page
- help tour positioning fix on credits page
Some of those changes are temporary, as more copy updates are on their way
[closes #107904580]

Add remaining copy changes

---

mtp_cashbook/templates/cashbook/dashboard.html

see https://www.pivotaltracker.com/story/show/108743768

Send the tour to the right step when dismissing

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_forms.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/transactions_history.html

so that google analytics can be used to monitor search parameters such, particularly the text-based search

Make transaction history search form work via a GET request

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_forms.py
mtp_cashbook/assets-src/javascripts/main.js
mtp_cashbook/assets-src/stylesheets/views/_history.scss
mtp_cashbook/templates/cashbook/transactions_history.html
test/features/history.feature
test/features/steps/shared.js

- make the search box look as intended
- readd the show-hide code and make it work in IE8
- fix the search box markup to make changes easier
- remove unnecessary table columns
- add tests

Use the latest history page designs and copy

---

mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/includes/table_actions.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
package.json

- remove links and what's not needed
- add specific print-only boxes
- make layout printer-friendly
[Updates: #109440804]

Improve printed pages

---

mtp_cashbook/assets-src/stylesheets/views/_batch.scss

Remove the left margin on the Done button line

---

mtp_cashbook/apps/feedback/urls.py
mtp_cashbook/settings/base.py
mtp_cashbook/templates/feedback/submit_feedback.html
mtp_cashbook/urls.py
requirements/base.txt

This consists of a basic form, which can be extended in
future.

Add feedback page for submission of Zendesk tickets

---

package.json

which themselves use the latest mojular that stops printing
things on the console.

Use latest common assets

---

mtp_cashbook/apps/cashbook/healthchecks.py
mtp_cashbook/settings/base.py
mtp_cashbook/urls.py
requirements/base.txt

depends on [django-moj-irat#1](https://github.com/ministryofjustice/django-moj-irat/pull/1)

Add a healthcheck.json view for IRaT support which tests MTP API & Zendesk connectivity

---

mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html

in order to display a message when necessary
[updates #110406604]

Use the new message box partial

---

mtp_cashbook/templates/cashbook/transaction_batch_list.html

From: https://notableapp.com/posts/1145743
[updates #109880716]

Add corrected copy for printout view

---

gulpfile.js
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/assets-src/javascripts/main.js
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/assets-src/stylesheets/views/_history.scss
mtp_cashbook/assets-src/stylesheets/views/_locked.scss
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/includes/batch_buttons.html
mtp_cashbook/templates/cashbook/includes/locked_buttons.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html

Replace guided tour on Payments and Dashboard pages with help popup

---

README.md

This is currently mostly about front-end commands. Feel free to let me know if anything's missing.

Reflect the current processes

---

mtp_cashbook/assets-src/javascripts/modules/batch-validation.js
mtp_cashbook/templates/cashbook/transaction_batch_list.html

And fix a markup bug which messed up the credit form validation

Tell GA the number of events submitted

---

mtp_cashbook/assets-src/javascripts/modules/batch-validation.js

- don't track incomplete submits, as it's not tracked by the popup
- track complete submits as virtual pageviews
- add code comments on the submit function

Improve google analytics tracking

---

mtp_cashbook/apps/cashbook/tests/test_functional.py

depends on [mtp-common#58](https://github.com/ministryofjustice/money-to-prisoners-common/pull/58)

Allow functional testing from the command line to choose the web driver

---

mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/apps/cashbook/urls.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/javascripts/main.js
mtp_cashbook/assets-src/javascripts/modules/batch-validation.js
mtp_cashbook/templates/cashbook/transaction_batch_list.html
package.json

to easily send custom pageviews from the page's markup or the JS code

Use the new GA module functionality

---

mtp_cashbook/apps/cashbook/tests/test_functional.py

depends on [mtp-api#104](https://github.com/ministryofjustice/money-to-prisoners-api/pull/104)

Tests can recreate data

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/templatetags/transactions.py
mtp_cashbook/apps/cashbook/tests/test_forms.py
mtp_cashbook/templates/cashbook/transactions_history.html

Depends on [money-to-prisoners-api#122](https://github.com/ministryofjustice/money-to-prisoners-api/pull/122)

Sort history page grouping by reverse chronological order and then prisoner number

---

mtp_cashbook/apps/cashbook/tests/test_functional.py
package.json
requirements/dev.txt
requirements/docker.txt

Depends on [mtp-utils#6](https://github.com/ministryofjustice/money-to-prisoners-utils/pull/6) and [mtp-common#96](https://github.com/ministryofjustice/money-to-prisoners-common/pull/96)

Add in-browser accessibility testing to functional tests

---

mtp_cashbook/apps/cashbook/views.py

[Updates https://www.pivotaltracker.com/n/projects/1214032/stories/115021955]

Improve the feedback to the user after releasing credits

---

mtp_cashbook/settings/base.py
mtp_cashbook/templates/base.html
mtp_cashbook/urls.py
requirements/base.txt

Allows user admins to create/update/delete oridinary
cashbook user accounts.

Add user management interface

---

mtp_cashbook/apps/cashbook/tests/test_functional.py

This ensures that the functional tests will work correctly
regardless of the initial state of the environment they are run
against.

Use generated user admin account for functional tests

---

mtp_cashbook/templates/cashbook/includes/locked_buttons.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html

Updates https://www.pivotaltracker.com/story/show/117518665

Make another round of copy changes

---

mtp_cashbook/assets-src/javascripts/main.js
package.json

Only through application calls to window.print
Part of https://www.pivotaltracker.com/story/show/108758158

Track with user clicks print

---

mtp_cashbook/templates/cashbook/includes/table_actions.html
package.json

https://www.pivotaltracker.com/story/show/108758234

Track when a user clicks 'select all'

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/settings/base.py
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html
mtp_cashbook/templates/feedback/submit_feedback.html
package.json
requirements/dev.txt
requirements/docker.txt

will not pass tests until [mtp-utils#13](https://github.com/ministryofjustice/money-to-prisoners-utils/pull/13) is merged and on pypi

Replace error summary and fields with shared templates from MTP-utils

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html

Part of https://www.pivotaltracker.com/story/show/117238367
and https://www.pivotaltracker.com/story/show/117518665

Amend copy in various places

---

mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html

Part of https://www.pivotaltracker.com/story/show/116045247

Indicate role of element for aria attributes

---

mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/templates/cashbook/transactions_history.html

to make more sense of the page number links
Part of https://www.pivotaltracker.com/story/show/116045247

Add invisible text which will be read by screen readers

---

Dockerfile
Makefile
find_common.py
mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_code_style.py
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/mtp_auth/urls.py
mtp_cashbook/settings/base.py
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/transaction_batch_list.html
mtp_cashbook/templates/cashbook/transactions_history.html
mtp_cashbook/templates/cashbook/transactions_locked.html
mtp_cashbook/templates/feedback/submit_feedback.html
mtp_cashbook/templates/mtp_auth/login.html
mtp_cashbook/urls.py
package.json
requirements/base.txt
requirements/dev.txt
requirements/docker.txt

This is the new package that combines common, utils and user-admin.

Use new mtp common

---

mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/includes/table_actions.html
mtp_cashbook/templates/cashbook/transactions_history.html

https://www.pivotaltracker.com/story/show/118084565

Remove remaining instances of 'payment'

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/settings/base.py
mtp_cashbook/templates/cashbook/transactions_history.html

These columns are relevant for debit card payments.

Add columns for payment method and intended recipient to history

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/templatetags/credits.py
mtp_cashbook/apps/cashbook/tests/test_forms.py
mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/apps/cashbook/urls.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/javascripts/modules/batch-validation.js
mtp_cashbook/templates/cashbook/credit_batch_list.html
mtp_cashbook/templates/cashbook/credits_history.html
mtp_cashbook/templates/cashbook/credits_locked.html
mtp_cashbook/templates/cashbook/dashboard.html

Changed language in source to refer to credits rather than
transactions.

Refactor cashbook to use credits endpoint instead of transactions

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/__init__.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/apps/mtp_auth/models.py
mtp_cashbook/apps/mtp_auth/urls.py
mtp_cashbook/settings/base.py
requirements/base.txt
requirements/dev.txt
requirements/docker.txt

…because it's not used elsewhere and is highly specialised for MTP services' setup

Merge MoJ Auth package into MTP Common

---

mtp_cashbook/assets-src/stylesheets/views/_history.scss
requirements/dev.txt
requirements/docker.txt

depends on [common#152](https://github.com/ministryofjustice/money-to-prisoners-common/pull/152)

Move pagination styles to common for reuse elsewhere

---

mtp_cashbook/apps/cashbook/tests/test_functional.py

to not flood MailGun with rubbish

Change functional test email address to one that's dropped by non-production environments

---

mtp_cashbook/apps/cashbook/views_training.py
mtp_cashbook/templates/training/training--intro.html

even though i disagree with new order of home page buttons :)

Update training to match order of credit history and in progress pages

---

mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/credits_history.html

like in security views in NOMS ops

Display truncated list of pages in history view

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_forms.py

The API now uses __gte, __lt rather than _0, _1.

Update received_at filter to use new API format

---

mtp_cashbook/assets-src/stylesheets/app.scss
mtp_cashbook/assets-src/stylesheets/views/_dashboard.scss
mtp_cashbook/templates/cashbook/dashboard.html

- added mtp- prefix to dashboard class names
- added comments to clarify application specific and govuk or mtp-common override styles

Adjusted css class names

---

mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/assets-src/stylesheets/views/_locked.scss
mtp_cashbook/templates/cashbook/credit_batch_list.html
mtp_cashbook/templates/cashbook/credits_history.html
mtp_cashbook/templates/cashbook/credits_locked.html
mtp_cashbook/templates/cashbook/includes/batch_buttons.html
mtp_cashbook/templates/cashbook/includes/locked_buttons.html

- add mtp- prefix to locked styles and implemented BEM for clarity
- amended class names where the same ones were found elsewhere in repo

Adjust css class names on styles for locked credits page

---

mtp_cashbook/assets-src/javascripts/modules/training.js
mtp_cashbook/assets-src/stylesheets/views/_training.scss
mtp_cashbook/templates/training/page.html
mtp_cashbook/templates/training/service-overview--day-1.html
mtp_cashbook/templates/training/service-overview--day-2.html
mtp_cashbook/templates/training/service-overview--day-3.html
mtp_cashbook/templates/training/service-overview--day-4.html
mtp_cashbook/templates/training/service-overview--day-5.html
mtp_cashbook/templates/training/survey-link.html
mtp_cashbook/templates/training/training--history.html
mtp_cashbook/templates/training/training--in-progress.html
mtp_cashbook/templates/training/training--intro.html
mtp_cashbook/templates/training/training--new.html

- added mtp- prefix for clarity
- implemented BEM naming

Adjust css class names for training pages

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/assets-src/stylesheets/views/_dashboard.scss
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/credit_batch_list.html
mtp_cashbook/templates/cashbook/dashboard.html
mtp_cashbook/templates/cashbook/includes/batch_table_actions.html
mtp_cashbook/translations/cy/LC_MESSAGES/django.po
mtp_cashbook/translations/en_GB/LC_MESSAGES/django.po

Additionally add number of reviewed credits to dashboard view context.

Add pre approval flag to context data in dashboard and crediting views

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/cashbook/tests/test_screenshots.py
mtp_cashbook/apps/cashbook/views.py

previously, new credits were not given in batches of 20

Change screenshot generation mocks to return appropriate data

---

mtp_cashbook/assets-src/javascripts/modules/sticky-header.js
mtp_cashbook/assets-src/stylesheets/views/_batch.scss
mtp_cashbook/templates/cashbook/credit_batch_list.html

- append sticker header to form, rather than body

Fix sticky header confirm button

---

mtp_cashbook/templates/training/service-overview--day-3.html
mtp_cashbook/translations/cy/LC_MESSAGES/django.po
mtp_cashbook/translations/en_GB/LC_MESSAGES/django.po

Amend training content to reflect the change from the Phoenix financial system to SOP (Single Operating Platform).

Phoenix to sop

---

Dockerfile
conf/uwsgi/cashbook.ini
mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tasks.py
mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/settings/base.py
mtp_cashbook/templates/cashbook/email/credited-confirmation.html
mtp_cashbook/templates/cashbook/email/credited-confirmation.txt
requirements/base.txt

This only applies to those credited via NOMIS integration, as
otherwise we cannot be certain that the prisoners actually received
the money.

Send email notification to sender when prisoner is credited

---

mtp_cashbook/apps/cashbook/forms.py
mtp_cashbook/apps/cashbook/tests/test_nomis_views.py
mtp_cashbook/assets-src/stylesheets/views/_progress_bar.scss
mtp_cashbook/templates/cashbook/new_credits.html
mtp_cashbook/templates/cashbook/processing_credits.html
requirements/dev.txt
requirements/docker.txt

Also fix progress bar and print links.

Fix credits retrieved

---

mtp_cashbook/assets-src/javascripts/modules/sticky-header.js

… used to assume that there is only one form on the page
Fixes #MTP-262

Fix sticky header attachment

---

Dockerfile
cashbook.ini
mtp_cashbook/assets-src/javascripts/modules/confirm-manual.js
mtp_cashbook/assets-src/javascripts/modules/print-batch.js
requirements/dev.txt
requirements/docker.txt

This updates
• the base container to Ubuntu Xenial
• node.js to version 8
• python to version 3.5

Docker upgrades

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/templates/cashbook/processed_credits_detail.html

Also populate current values in search fields.

Add total to processed credits batch page

---

mtp_cashbook/apps/disbursements/forms.py
mtp_cashbook/apps/disbursements/tests/test_search.py
mtp_cashbook/templates/disbursements/search.html

and move NOMIS reference to the correct point in history list

Add disbursement invoice number to "payments made" search listings

---

mtp_cashbook/apps/disbursements/forms.py
mtp_cashbook/templates/disbursements/search.html

Do not show rejected disbursements on payments made page

---

mtp_cashbook/templates/mtp_common/user_admin/sign-up-success.html
requirements/dev.txt
requirements/docker.txt

to make it clear that it's the prison's admin that deals with requests

Clarify success message when requesting access

---

requirements/dev.txt
requirements/docker.txt

… as it's true 99% of the time

Add note to login page about username==Quantum ID

---

mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/assets-src/stylesheets/app-ie8.scss
mtp_cashbook/assets-src/stylesheets/views/_login.scss
mtp_cashbook/templates/base.html
mtp_cashbook/templates/cashbook/processed_credits.html
mtp_cashbook/templates/cashbook/search.html
mtp_cashbook/templates/disbursements/search.html
mtp_cashbook/templates/mtp_auth/login.html
requirements/dev.txt
requirements/docker.txt

Add a banner for IE8-only display to indicate that users should switch browser

---

mtp_cashbook/settings/base.py
requirements/dev.txt
requirements/docker.txt

This adds the cloud platform migration middleware and sets up the related settings values as env vars.

Add support for cloud platform migration

---

mtp_cashbook/apps/feedback/views.py

not directly related to, but helps with ticket MTP-1366

Make it clearer who Zendesk tickets are meant for

---

mtp_cashbook/apps/disbursements/urls.py
requirements/base.txt
requirements/dev.txt
requirements/docker.txt

…and update uwsgi and django-anymail dependencies that include bug fixes [MTP-1519](https://dsdmoj.atlassian.net/browse/MTP-1519) (depends on [common-380](https://github.com/ministryofjustice/money-to-prisoners-common/pull/380))
also fixes display of focused links in Chrome/Edge [MTP-1514](https://dsdmoj.atlassian.net/browse/MTP-1514)

Use a single consistent version requirement for Django in all apps

---

mtp_cashbook/templates/policy-change-info.html
mtp_cashbook/templates/policy-change-warning-landing.html
mtp_cashbook/templates/policy-change-warning.html

Jira: https://dsdmoj.atlassian.net/browse/MTP-1663
Sharon has some slight updates to the cashbook copy shipped recently,
this commit adds those changes and equivilent changes for post policy
change info.

MTP-1663 Copy updates to Cashbook policy change info

---

mtp_cashbook/templates/cashbook/faq.html

Cashbook FAQ: Removed spurious speak mark char

---

.gitignore
mtp_cashbook/apps/mtp_auth/forms.py
mtp_cashbook/apps/mtp_auth/tests/test_views.py
mtp_cashbook/templates/mtp_common/user_admin/new-account-request-ticket.txt
requirements/base.txt
requirements/dev.txt

Jira: https://dsdmoj.atlassian.net/browse/MTP-1805
Linked PRs:
* Common: https://github.com/ministryofjustice/money-to-prisoners-common/pull/412
* API: https://github.com/ministryofjustice/money-to-prisoners-api/pull/642

MTP-1805 request an account

---

.gitignore
mtp_cashbook/assets-src/components/disbursements/_search-filters.scss
mtp_cashbook/assets-src/components/print-link-target/index.js
mtp_cashbook/templates/cashbook/includes/manual_credit_table.html
mtp_cashbook/templates/cashbook/new_credits.html
mtp_cashbook/templates/disbursements/pending_detail.html
mtp_cashbook/templates/disbursements/search.html
mtp_cashbook/templates/mtp_common/user_admin/move-prison.html
requirements/base.txt
requirements/dev.txt

Largely updates upstream dependencies, but also includes new button group visual component (buttons placed side-by-side) from GOV.UK design system and better print layouts.

Bundle of fixes and updates related to GOV.UK Design System update

---

mtp_cashbook/apps/cashbook/tasks.py
mtp_cashbook/apps/cashbook/tests/test_views.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/apps/disbursements/forms.py
mtp_cashbook/apps/disbursements/views.py
requirements/base.txt
requirements/dev.txt

Jira: https://dsdmoj.atlassian.net/browse/MTP-1863
* Moved dynamic fields out of logger.error/warning and exceptions to allow for sentry to deduplicate
Depends on [common#419](https://github.com/ministryofjustice/money-to-prisoners-common/pull/419)

MTP-1863 Remove remaining identifiers from exceptions and attach to sentry metadata

---

mtp_cashbook/urls.py

C.f. https://ministryofjustice.github.io/security-guidance/implement-security-txt/

Add /.well-known/security.txt redirect

---

mtp_cashbook/settings/base.py

…at 30% sample rate in production (this is a medium traffic app) and 100% in other environments.

Turn on Sentry.io performance monitoring

---

mtp_cashbook/__init__.py
mtp_cashbook/apps/cashbook/tests/__init__.py
mtp_cashbook/apps/cashbook/tests/test_code_style.py
mtp_cashbook/apps/cashbook/tests/test_functional.py
mtp_cashbook/apps/cashbook/tests/test_misc_views.py
mtp_cashbook/apps/cashbook/urls.py
mtp_cashbook/apps/cashbook/views.py
mtp_cashbook/apps/mtp_auth/urls.py
mtp_cashbook/apps/settings/forms.py
mtp_cashbook/apps/settings/tests/test_credit_notice_emails.py
mtp_cashbook/apps/settings/urls.py
mtp_cashbook/apps/settings/views.py
mtp_cashbook/middleware.py
mtp_cashbook/misc_forms.py
mtp_cashbook/misc_views.py
mtp_cashbook/settings/__init__.py
mtp_cashbook/settings/base.py
mtp_cashbook/settings/ci.py
mtp_cashbook/settings/docker.py
mtp_cashbook/templates/confirm-credit-notice-emails.html
mtp_cashbook/templates/mtp_common/components/header-app-links.html
mtp_cashbook/templates/settings/change-credit-notice-emails.html
mtp_cashbook/templates/settings/settings.html
mtp_cashbook/urls.py
mtp_cashbook/utils.py

Depends on [api#685](https://github.com/ministryofjustice/money-to-prisoners-api/pull/685)

Editing of email addresses for prisoner credit notice (aka credit slips)

---

mtp_cashbook/apps/cashbook/notify/templates.py

This reverts commit b1290749d6235804f7779c86e500a2209c164e40.

Remove PVB survey invite from confirmation email

---

mtp_cashbook/templates/disbursements/handover.html
mtp_cashbook/templates/govuk-frontend/components/footer.html
requirements/base.txt
requirements/dev.txt

…fixing templates to work with latest GOV.UK frontend

Update mtp-common and dependencies

---

mtp_cashbook/apps/disbursements/forms.py
mtp_cashbook/apps/disbursements/templatetags/disbursements.py
mtp_cashbook/apps/disbursements/tests/test_create.py
mtp_cashbook/apps/disbursements/views.py
requirements/base.txt
requirements/dev.txt

MTP-1961: Attempt to upgrade to Django 3.2
