ministryofjustice/money-to-prisoners-cashbook

.dockerignore, README.md, docker-compose.yml, package.json
This allows a developer to run the project and develop locally using `docker-compose` without having to have anything else installed. 
The readme has been updated to show how to do this on a Mac/using boot2docker.
=> Local Development Environment #95958132

Dockerfile, mtp_cashbook/settings/base.py, mtp_cashbook/templates/base.html
Jenkins needs to be able to extract assets from the container when deploying. To allow it to do that, compile them then collect them all into one place (defined by `mtp_cashbook.settings.*.STATIC_ROOT`).
Because of the way we're deploying them to S3, `STATIC_ROOT` needs to be the same as `STATIC_URL`, or we'll be referring to invalid URLs.
Also use `npm install` instead of `bower install` so that it installs gulp et al. in more accessible paths.
=> Collect static assets for production

docker-compose.yml
After setting up a new dev environment for the API server project
I have found some better ways of doing things in a local dev
environment using docker-compose.
- The docker-compose up command now installed python dev
dependencies before running the server
- The npm install command in the gulp container now shares
a .npm cache with the host
- PIP now shares a PIP_DOWNLOAD_CACHE with the host so it
doesn't need to download the same dependencies every
time
=> Make running a local dev environment quicker

Dockerfile
After discussing with platofrms team, this isn't a good idea. Their own
docker base images don't do this and we want to be consistent.
=> Don't set default timezone to be Europe/London

README.md
Upon installing docker for the first time I found `init` was also needed.
=> Update README with VM initialise instructions

README.md, mtp_cashbook/apps/core/admin.py, mtp_cashbook/apps/core/tests.py, mtp_cashbook/apps/mtp_auth/__init__.py, mtp_cashbook/apps/mtp_auth/api_client.py, mtp_cashbook/apps/mtp_auth/backends.py, mtp_cashbook/apps/mtp_auth/exceptions.py, mtp_cashbook/apps/mtp_auth/forms.py, mtp_cashbook/apps/mtp_auth/middleware.py, mtp_cashbook/apps/mtp_auth/models.py, mtp_cashbook/apps/mtp_auth/tests/test_forms.py, mtp_cashbook/apps/mtp_auth/tests/test_views.py, mtp_cashbook/apps/mtp_auth/urls.py, mtp_cashbook/apps/mtp_auth/views.py, mtp_cashbook/settings/base.py, mtp_cashbook/templates/base.html, mtp_cashbook/templates/core/index.html, mtp_cashbook/templates/mtp_auth/login.html, mtp_cashbook/urls.py, requirements/base.txt, requirements/dev.txt
This allows a valid user to log into the cashbook app using oauth2 against the API app.
Custom login, logout and authentication logic is required as the standard django behaviour
relies on database tables.
Unfortunately, I had to borrow some django code and change it accordingly in order to support our authentication method.
Use the mock python library for mocking the API connection so that unit tests can run
without dependencies.
=> Allow users to log into cashbook

README.md, docker-compose.yml
When running in docker-compose with boot2docker, the cashbook attempts to connect to the default API URL (`http://localhost:8000`) but fails because `localhost` refers to the current container.
To resolve that, we need to pass the `API_URL` environment variable with the boot2docker VM's IP into the container. By specifying `API_URL` in `docker-compose.yml` with no value, docker-compose will read the value from the host, if it exists, and pass that to the container.
=> Pass the host's API_URL to the cashbook container

mtp_cashbook/apps/mtp_auth/__init__.py, mtp_cashbook/apps/mtp_auth/api_client.py, mtp_cashbook/apps/mtp_auth/backends.py, mtp_cashbook/apps/mtp_auth/exceptions.py, mtp_cashbook/apps/mtp_auth/forms.py, mtp_cashbook/apps/mtp_auth/models.py, mtp_cashbook/apps/mtp_auth/tests/test_api_client.py, mtp_cashbook/apps/mtp_auth/tests/test_forms.py, mtp_cashbook/apps/mtp_auth/tests/test_views.py, mtp_cashbook/apps/mtp_auth/tests/utils.py, mtp_cashbook/settings/base.py, mtp_cashbook/settings/prod.py, requirements/base.txt, requirements/dev.txt
This changes the way the code calls the api simplifying its logic.
Only 2 functions are exposed:
- `api_client.authenticate` which authenticates against the api
- `api_client.get_connection` which returns a slumber connection able
to deal with refreshing the access token automatically if needed.
In this way, the views can just use the connection without worrying about
tokens at all.
=> Refactor api_client to support refresh tokens automatically.

mtp_cashbook/settings/base.py
This is so that we can use the request object in our django templates
(e.g. request.user.username)
=> Add request to context processors

docker-compose.yml
The djangogulpserve container uses the same image as the django container, so we should explicitly indicate that's what we want to avoid building it twice. If djangogulpserve needed to be run on its own
this would break, but we never actually need that because it only exists for serving assets during development.
Also make the the environment variable passed to `--port` consistent with the one used for `--host`.
=> Stop docker-compose building our image twice

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/cashbook/tests.py, mtp_cashbook/apps/cashbook/tests/test_forms.py, mtp_cashbook/apps/cashbook/views.py, mtp_cashbook/apps/core/templatetags/core.py, mtp_cashbook/templates/base.html, mtp_cashbook/templates/cashbook/includes/batch_buttons.html, mtp_cashbook/templates/cashbook/transaction_batch_list.html, mtp_cashbook/templates/core/index.html, mtp_cashbook/urls.py
This changes the transaction batch view to being a FormView so that we can
validate and manage the it easily.
Saving the form will credit the selected transactions and discard the rest.
Saving the form passing discard='1' will discard all the transactions.
=> Implement credit/discard view

Dockerfile
`ADD`ing the project directory before `npm install` meant that any change, anywhere in the project directory, would invalidate the Docker build cache for the `npm install` step. Given that this step involves a number of network requests, and installs npm and bower packages, it ends up being very slow.
Explicitly `ADD`ing bower/npm package config (and the README, which is apparently used for the npm package description) means Docker only invalidates the cache (and, thus, re-runs the `npm install`) when these files change. This dramatically improves rebuild times (from ~2m30 to <10s) for the majority of changes.
=> Improve Docker caching of JavaScript dependencies

.gitignore, Makefile, README.md
There are a handful of complex, conditional steps people have to jump through before being able to work with our codebase. This attempts to automate them all using `make`, including starting `boot2docker` (if it's installed; otherwise we assume it's unnecessary), and means we can simplify the process of working with our code.
=> Automate the getting started process

Makefile, README.md, mtp_cashbook/apps/cashbook/admin.py, mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/cashbook/models.py, mtp_cashbook/apps/cashbook/templatetags/currency.py, mtp_cashbook/apps/core/models.py, mtp_cashbook/apps/core/views.py, mtp_cashbook/apps/mtp_auth/forms.py, mtp_cashbook/apps/mtp_auth/tests/test_api_client.py, mtp_cashbook/apps/mtp_auth/urls.py, mtp_cashbook/settings/__init__.py, mtp_cashbook/settings/base.py, mtp_cashbook/settings/prod.py, mtp_cashbook/wsgi.py, requirements/dev.txt, setup.cfg
We need an easy way of checking that our code matches [pep8](https://www.python.org/dev/peps/pep-0008/) (Python's style guide). This adds `make lint` for that purpose, and fixes existing linting errors.
It's probably worth reviewing this one commit at a time. Once it's merged to master, I'll look at linting in Jenkins.
=> Add linting helper and fix existing linting issues

Makefile
If we change our JavaScript dependencies, we should rebuild the container.
=> Make container builds rely on JS dependencies

mtp_cashbook/assets-src/stylesheets/app.scss
Currently getting an 'Invalid US-ASCII character "\xE2"' error in the compiled CSS file
=> Fix invalid character error in Sass

Dockerfile
See 6fcc62845dcbb43d3b90bcbf10721f6213da3716. This also installs the UTF
locale on the box and sets it in the LC_CTYPE env var as suggested here
https://github.com/sindresorhus/gulp-ruby-sass/issues/232
=> Install en_US.UTF-8 locale to fix assets

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/cashbook/tests/test_forms.py, mtp_cashbook/apps/cashbook/tests/test_views.py, mtp_cashbook/apps/cashbook/views.py
Changes needed after namespaced cashbook transactions endpoints.
previously: /transactions/
now: /cashbook/transactions/
=> Namespace cashbook transactions

bower.json, mtp_cashbook/assets-src/javascripts/modules/moj.feature-tour.js, mtp_cashbook/templates/cashbook/dashboard.html, mtp_cashbook/templates/cashbook/transaction_batch_list.html
- Remove JS error when no `tour` object exists
- Update hopscotch to avoid multiple highlight containers being added even when one already exists or the tour isn't active.
=> Feature tour enhancements

mtp_cashbook/assets-src/javascripts/modules/moj.unload.js, mtp_cashbook/templates/cashbook/includes/batch_buttons.html, mtp_cashbook/templates/cashbook/transaction_batch_list.html
As a monies clerk I want to be warned if I leave the batch screen and I have ticked some transactions so I submit my credited transactions.
[finishes #103089538]
=> Unload prompt

mtp_cashbook/apps/cashbook/forms.py
This fixes a bug caused by the cashbook client not filtering by
logged-in user when requesting locked transactions.
This caused prison clerks from the same prison to see all the locked
transactions.
=> Locked transactions view only shows the ones locked by user

bower.json, mtp_cashbook/assets-src/stylesheets/app.scss, tasks/sass.js
Image reference was incorrect for fallback image which meant IE8 wasn't getting a semi transparent background.
[Delivers #104003626]
**Before:**
**After:**
=> Patch hopscotch highlight to fix image referance

mtp_cashbook/urls.py
For consistency with the other front-end applications.
=> Remove auth prefix from login urls

mtp_cashbook/apps/core/testing/testcases.py, mtp_cashbook/apps/mtp_auth/urls.py, mtp_cashbook/settings/base.py, mtp_cashbook/templates/base.html, mtp_cashbook/urls.py
This is to make it easier to reuse templates across the different
projects.
=> Remove 'auth' URL namespace for consistency with other front-ends

gulpfile.js
- watch directories passed as arguments to gulp command (eg, common assets)
- delay browsersync reload, else it happens before tasks end
This seems to be due to a gulp-browsersync bug
=> improve watch tasks and browsersync

test/features/user_signin.feature
generated users have a different naming scheme now
depends on [api#57](https://github.com/ministryofjustice/money-to-prisoners-api/pull/57)
=> Fix user login cucumber integration test

mtp_cashbook/settings/base.py, mtp_cashbook/templates/base.html, package.json
depends on [django-utils#7](https://github.com/ministryofjustice/django-utils/pull/7)
NB: tests will likely fail until that PR is merged
=> Add Sentry exception handling for JavaScript

mtp_cashbook/apps/feedback/urls.py, package.json
This page will confirm that the ticket was submitted and
provide a link back to where the user was when they decided
to submit feedback.
=> Provide url for a post-feedback submission success page

.gitignore, mtp_cashbook/apps/cashbook/tests/test_browser.py, mtp_cashbook/apps/cashbook/tests/test_functional.py, package.json, requirements/dev.txt
Not to be merged, but demonstrating a proposal to replace JS functional tests and implement them as Django tests instead. 
The proposal includes no longer using cucumber as the team doesn't have a workflow where plain language tests are necessary. This would remove the complexity to translate the cucumber tests into js+webdriver. Moving the new django tests along with the existing unit tests makes it simpler to run and maintain the whole test suite in one go.
To be discussed.
=> Add python functional tests

mtp_cashbook/settings/base.py
• all logs are prepended with their level
• all logs of level INFO or higher will be output to the console and ELK
• all logs of level ERROR or higher will also be sent to Sentry if configured
=> Make django logging consistent between apps

mtp_cashbook/assets-src/javascripts/modules/batch-validation.js
This is not strictly necessary to follow a user journey, but makes it easier
to read the GA funnel
=> Add a virtual pageview when the confirmation dialog opens

mtp_cashbook/templates/cashbook/transactions_history.html
This applies to transactions which are the result of an online payment.
=> Show intended recipient where available in history view

mtp_cashbook/apps/cashbook/templatetags/transactions.py
…so they display correctly during BST for midnight transactions
=> Convert transaction date-time fields to local time

mtp_cashbook/apps/feedback/urls.py
The path changed as a result of changes to mtp-common
=> Correctly specify path of feedback_success template

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/assets-src/stylesheets/app.scss, requirements/dev.txt, requirements/docker.txt
visually; they're still there for screen readers
=> Remove more full stops at the end of error messages

requirements/dev.txt, requirements/docker.txt
This is for compatibility with API changes to user prison
retrieval in the user admin.
=> Increase version of mtp-common required to 3.10.0

mtp_cashbook/apps/cashbook/templatetags/credits.py, mtp_cashbook/assets-src/stylesheets/views/_history.scss, mtp_cashbook/templates/cashbook/credits_history.html
Anonymous payments are displayed separately to other payments
and have an orange banner.
=> Display 'anonymous' payments in cashbook history screen

mtp_cashbook/apps/cashbook/tests/test_functional.py
This fills up the Mailgun log with complaints about being unable
to find the MX record at v.com.
=> Remove non-local email address from functional tests

mtp_cashbook/assets-src/javascripts/main.js, mtp_cashbook/assets-src/javascripts/modules/batch-validation.js, mtp_cashbook/assets-src/javascripts/modules/running-total.js, mtp_cashbook/assets-src/javascripts/modules/sticky-header.js, mtp_cashbook/assets-src/stylesheets/app-ie6.scss, mtp_cashbook/assets-src/stylesheets/app-ie7.scss, mtp_cashbook/assets-src/stylesheets/app-ie8.scss, mtp_cashbook/assets-src/stylesheets/app.scss, mtp_cashbook/assets-src/stylesheets/views/_batch.scss, mtp_cashbook/settings/base.py, mtp_cashbook/settings/docker.py, mtp_cashbook/settings/jenkins.py, mtp_cashbook/templates/cashbook/credit_batch_list.html, mtp_cashbook/templates/cashbook/credits_history.html, mtp_cashbook/templates/cashbook/credits_locked.html, mtp_cashbook/templates/cashbook/dashboard.html, mtp_cashbook/templates/cashbook/includes/print_dialog.html, mtp_cashbook/templates/cashbook/includes/table_actions.html, mtp_cashbook/templates/feedback/submit_feedback.html, requirements/dev.txt, requirements/docker.txt, run.sh, webpack.config.js
* use latest common
* require js scripts the standard way
* add stylesheets for old ie versions
* align to govuk visual styles,
* use govuk classes, markup and template
* find new govuk-templates
* adapt run script and webpack config
* use display:none to avoid FOUCs
* Fix heading hierarchy
* remove <dialog> as not supported by the version of html5shiv in govuk_template
* remove align attribute (wtf)
=> remove Mojular:

mtp_cashbook/apps/cashbook/tests/test_views.py, mtp_cashbook/apps/mtp_auth/urls.py, requirements/dev.txt, requirements/docker.txt
This is no longer needed as application restrictions are checked
in the API.
=> Remove 'restrict_applications' argument to login view

mtp_cashbook/apps/cashbook/templatetags/credits.py, requirements/dev.txt, requirements/docker.txt
Previously anonymous and uncredited payments were being intermingled.
=> Make credit ordering on history screen consistent

mtp_cashbook/apps/cashbook/tests/test_functional.py
The precise size of text/margins is not a behaviour that needs
to be specified in tests.
=> Remove functional tests for element dimensions

mtp_cashbook/apps/cashbook/urls.py, mtp_cashbook/apps/cashbook/views.py, mtp_cashbook/assets-src/stylesheets/app.scss, mtp_cashbook/templates/base.html, mtp_cashbook/templates/cashbook/inactive_password_change.html, requirements/dev.txt, requirements/docker.txt
- create inactive 'change password' template for test environment, so passwords cannot be altered during testing
- add url and view for 'inactive_password_change'
- add styling to grey out inactive form
- update requirements to use latest mtp-common version
=> Show inactive 'change password' page when in test environment

mtp_cashbook/assets-src/stylesheets/views/_training.scss
Screenshots were not being displayed correctly on IE8 as their
container maintained the unresized width or something like that.
=> Show screenshots correctly on IE8

mtp_cashbook/assets-src/stylesheets/views/_dashboard.scss, mtp_cashbook/templates/base.html, mtp_cashbook/templates/cashbook/dashboard.html
- Move the training site text to the phase banner.
- Move the explanatory blurb a bit closer to the header.
=> Reorganise explanatory text on cashbook homepage

mtp_cashbook/apps/cashbook/views_training.py, mtp_cashbook/assets-src/javascripts/modules/training.js, mtp_cashbook/assets-src/stylesheets/views/_training.scss, mtp_cashbook/settings/base.py, mtp_cashbook/templates/cashbook/credit_batch_list.html, mtp_cashbook/templates/cashbook/credits_history.html, mtp_cashbook/templates/cashbook/credits_locked.html, mtp_cashbook/templates/cashbook/dashboard.html, mtp_cashbook/templates/cashbook/inactive_password_change.html, mtp_cashbook/templates/training/page.html, mtp_cashbook/templates/training/service-overview--day-1.html, mtp_cashbook/templates/training/service-overview--day-2.html, mtp_cashbook/templates/training/service-overview--day-3.html, mtp_cashbook/templates/training/service-overview--day-4.html, mtp_cashbook/templates/training/service-overview--day-5.html, mtp_cashbook/templates/training/training--history.html, mtp_cashbook/templates/training/training--in-progress.html, mtp_cashbook/templates/training/training--intro.html, mtp_cashbook/templates/training/training--new.html, requirements/dev.txt, requirements/docker.txt
… and always show page titles in the training section (to have somewhere to anchor the language selector)
off on prod
=> Add language switching

mtp_cashbook/assets-src/stylesheets/views/_history.scss
- to stop right-hand totals being clipped on IE8
=> Adjust padding on collapsing header

mtp_cashbook/apps/cashbook/views.py
When the user has credits locked to them they will only see those when
clicking through to the processing screen, not any additional available
credits.
=> Display correct number of credits that will be shown when they are locked

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/templates/cashbook/credits_history.html
The page links on the history page were not including the current
query parameters.
=> Maintain search parameters across multiple history pages

mtp_cashbook/assets-src/javascripts/modules/running-total.js
Larger credit amounts with a comma in would be parsed as if the
comma were a decimal i.e. £1,000 would be added to the running
total as £1.
=> Fix JS bug with running total summation

mtp_cashbook/assets-src/stylesheets/views/_credits.scss, mtp_cashbook/templates/cashbook/new_credits.html
Removes the 'select' boxes from the printout as they should not be
using it for any processing anymore.
=> Alter print layout for post-NOMIS cashbook screens

mtp_cashbook/apps/cashbook/tasks.py
We have seen some instances of arguments being too large for this
job.
=> Pass credits as body params to spooler job

mtp_cashbook/apps/cashbook/tasks.py
This event is not an error, and it is a typical occurrence (even
if not an ideal one).
=> Downgrade log level of manual crediting event to warning

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/cashbook/tasks.py, requirements/dev.txt, requirements/docker.txt
This is due to SSL handshake failures when the NOMIS API is under
heavy load - using a session and a connection pool to reuse connections
avoids some of this overhead.
=> Maintain a thread local requests session for connections to NOMIS

mtp_cashbook/assets-src/javascripts/modules/print-batch.js
Firefox will not print a hidden iframe, so have changed hiding method
to displaying it off the page.
Firefox also does an async print() call, so the iframe was being removed
before it could be printed. Have changed the iframe removal to listen
for the `afterprint` event.
=> Fix printing of processed credits from list page on firefox

mtp_cashbook/apps/disbursements/views.py
If the user enters the create disbursement flow from the start page,
any previously entered form data from any incomplete disbursement
should be cleared.
=> Clear entered disbursement data if coming from start page

setup.cfg
…because `pep8-naming` has been fixed
=> Restore lowercase name checks

README.md, mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/disbursements/forms.py, mtp_cashbook/apps/disbursements/tests/test_confirm.py, mtp_cashbook/apps/disbursements/tests/test_search.py
This:
- adds/corrects a few lines in the README
- removes unused lines
- makes sure mutable data structures are not used for arg defaults
- changes another couple of things
The intention is to eventually add `flake8-bugbear` and `flake8-quotes` to mtp_common.
=> Housekeeping

mtp_cashbook/apps/cashbook/tests/__init__.py, mtp_cashbook/apps/cashbook/tests/test_views.py, mtp_cashbook/apps/disbursements/tests/test_confirm.py, mtp_cashbook/apps/disbursements/tests/test_create.py, mtp_cashbook/settings/base.py, requirements/dev.txt, requirements/docker.txt
This adds support for the new NOMIS Elite2 auth and API.
It mainly refactors the tests to mock the methods of the nomis library instead of mocking the nomis responses; this way we don't leak any internal nomis logic.
=> Nomis Elite2 API

.circleci/config.yml, .github/CODEOWNERS, Dockerfile, README.md, mtp_cashbook/apps/cashbook/metrics.py, mtp_cashbook/apps/cashbook/tasks.py, mtp_cashbook/apps/disbursements/forms.py, mtp_cashbook/apps/disbursements/metrics.py, mtp_cashbook/apps/disbursements/views.py, mtp_cashbook/settings/base.py, mtp_cashbook/urls.py, requirements/dev.txt, requirements/docker.txt
- As apps are now able to discover each other, many environment variables are now redundant so they can be removed
- Apps now use base Docker images built by this repository (pulling from ECR or building locally) – this speeds up builds and ensures they have the same base OS
- Add prometheus service monitors for all apps
- Depends on [mtp-deploy#282](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/282)
=> Remove template-deploy artefacts

mtp_cashbook/settings/base.py, requirements/dev.txt, requirements/docker.txt
The new endpoint that HMPPS has chosen does not include `/elite2api/` in the URL. Because this is a breaking change and client apps must have updated settings, it seems safest to require new settings names entirely. The settings names are now more descriptive of what HMPPS is calling the associated components.
Depends on [common-383](https://github.com/ministryofjustice/money-to-prisoners-common/pull/383) and [deploy-305](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/305).
[MTP-1484](https://dsdmoj.atlassian.net/browse/MTP-1484)
=> Update Prison API (i.e. NOMIS) connector url handling

mtp_cashbook/apps/cashbook/tests/test_misc_views.py, mtp_cashbook/misc_views.py, mtp_cashbook/templates/policy-change-warning-credits.html, mtp_cashbook/templates/policy-change-warning-disbursements.html, mtp_cashbook/templates/policy-change-warning-landing.html, mtp_cashbook/templates/policy-change-warning.html, mtp_cashbook/urls.py
This is the changed warning for upcoming policy changes, linking to a page with full details on changes rather than including longer copy on credit/disbursement changes in pages regularly used for work purposes. It avoids the need to have dismiss-able notifications and having to manage state of a user dismissing the notice etc.
Landing Page
Credits page
Disbursements
Detail page
=> Mtp 1591 cashbook policy change banner Version 2

mtp_cashbook/apps/cashbook/tasks.py, mtp_cashbook/apps/cashbook/tests/test_views.py, mtp_cashbook/templates/cashbook/email/credited-confirmation.html, mtp_cashbook/templates/cashbook/email/credited-confirmation.txt
`short_ref_number` was being used in place of `short_payment_ref` by mistake.
[MTP-1793](https://dsdmoj.atlassian.net/browse/MTP-1793)
=> Use correct payment ref field from mtp-api's credit response

requirements/base.txt
Bumped `mtp-common` to ~`11.0.1`~ `11.1.0` and removed dependencies already requested there to reduce duplication.
⚠️ **NOTE**: This is a major version bump and `mtp-common` `11.x` includes other changes (e.g. GDS Design System) so merge/release this may require some coordination/[depends on this PR](https://github.com/ministryofjustice/money-to-prisoners-cashbook/pull/537).
See
---
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1537
=> MTP-1537: Removed dependencies already in mtp-common

mtp_cashbook/apps/cashbook/urls.py, mtp_cashbook/apps/cashbook/views.py, mtp_cashbook/settings/base.py, mtp_cashbook/templates/cashbook/faq.html, mtp_cashbook/templates/mtp_common/components/header-app-links.html
The 'Get help' tab doesn't take the user directly to the page to contact
us anymore, instead an FAQ is presented to the user with useful/more
appropriate actions whenever possible.
The user can still reach the 'Contact us' (a.k.a `cashbook_submit_ticket`)
page from the FAQ page.
⚠️ **NOTE**: This PR is currently based on [`govuk-design-system` branch/PR](https://github.com/ministryofjustice/money-to-prisoners-cashbook/pull/537).
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1833
=> Cashbook (signed in) FAQ

mtp_cashbook/misc_views.py, mtp_cashbook/templates/faq.html, mtp_cashbook/templates/govuk-frontend/components/footer.html, mtp_cashbook/templates/mtp_auth/login.html, mtp_cashbook/urls.py
Added an FAQ page which user can refer to when he's not signed it.
The 'Get help' link when the user is not signed it will now take them
to this page instead of directly to the "Contact us".
⚠️ **NOTE**: This is based off [the GDS Design System branch/PR](https://github.com/ministryofjustice/money-to-prisoners-cashbook/pull/537).
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1834
=> FAQ when user signed out

mtp_cashbook/apps/feedback/forms.py, mtp_cashbook/templates/mtp_common/feedback/submit_feedback.html
- Remove lead paragraph
- Changed textarea label to 'Please give details'
Also
- Made 'Your email address' field mandatory.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1838
**NOTE**: As part of this ticket we're reviewing the exact copy of the pre-populated text which comes from the FAQ. This is independent from this change set and I could either add to this PR later on or make that change in a separate PR.
=> MTP-1838: Simplify 'Contact us' form

mtp_cashbook/templates/cashbook/faq.html, mtp_cashbook/templates/faq.html
Updated the pre-populated messages in the 'Contact us' form for some
of the links in the FAQs as per [copy document](https://docs.google.com/document/d/1n6BM4nPkJmnL7fOFSpRk-pFyxUUUo1Z-Zho6GmC3kzo/edit).
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1838
=> MTP-1838: Update copy of pre-populated 'Contact us' from FAQs

mtp_cashbook/templates/disbursements/pending_detail.html
…because they are _not_ visible in history section (under “Payments made”) and have not been for a while.
=> Remove incorrect information about user-cancelled disbursements

mtp_cashbook/apps/cashbook/tests/test_views.py, mtp_cashbook/apps/cashbook/views.py, mtp_cashbook/apps/disbursements/tests/test_search.py, mtp_cashbook/apps/disbursements/views.py, mtp_cashbook/templates/disbursements/search.html, mtp_cashbook/utils.py
Currently all credits are shown by default which is slow and probably
adds more unnecessary pressure to the database.
=> MTP-1925: Processed credits forms show last month by default

mtp_cashbook/apps/cashbook/forms.py, mtp_cashbook/apps/disbursements/forms.py, mtp_cashbook/apps/disbursements/tests/test_search.py
Clear a form default date means that query parameter is set blank.
Unfortunately these blank query params were ignored (we think this may be
to make the URL look cleaner)
Removing the logic that removes `None` query params should fix this issue.
=> MTP-1925: Clearing a form is lost when changing pages

cashbook.ini, mtp_cashbook/settings/base.py, mtp_cashbook/tasks.py, requirements/base.txt, requirements/dev.txt
uWSGI now runs in lazy mode such that each process loads its own complete application rather than forking the master. This now requires the spooler to setup django.
Lazy apps are needed if telemetry is to be sent to Azure Application Insights: the `opencensus` library starts a background thread on launch to transport telemetry to Azure, but if uWSGI loads the application and _then_ forks, this thread is no longer accessible from the new process.
In `prod` environment:
• `mtp` logs of level INFO and higher
• other logs of level WARNING and higher
• 10% of requests traces
…will be sent.
Depends on [common#539](https://github.com/ministryofjustice/money-to-prisoners-common/pull/539).
=> MTP-1921: Add Azure Application Insights request tracing and logging

mtp_cashbook/assets-src/components/cashbook/select-all.js, mtp_cashbook/assets-src/components/disbursements/index.js, mtp_cashbook/templates/mtp_auth/login.html, requirements/base.txt, requirements/dev.txt
… and use new password input component on login page
=> MTP-1980: Upgrade to govuk-frontend 5.3
